### ISSUE TITLE
If the lowest temperature is 0 degrees, the graph is not displayed correctly.

### ISSUE THREAD

**Issue by Murianwind** [pkissling/clock-weather-card#100]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

![화면 캡처 2022-11-01 093705](https://user-images.githubusercontent.com/6447460/199134360-bcc8af7b-7409-4858-aca2-05fab99416d1.png)
![화면 캡처 2022-11-01 093729](https://user-images.githubusercontent.com/6447460/199134367-ce66717e-deb9-4ccf-af32-8c33b2f22e73.png)

If the lowest temperature is 0 degrees, the graph will not show the lowest temperature. The graph shows the highest temperature as the lowest temperature.
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by pkissling** [comment]
hi @Murianwind,

thanks for reporting. gonna have a look

**Comment by pkissling** [comment]
i just fixed the issue you reported. gonna create a new release right now. please also consider #96 where i changed the Korean language code from `kr` to `ko`. this otherwise caused some issues whenever the provided `locale` was passed to other third party libraries. (`kr` translates to *Kanuri*) https://www.loc.gov/standards/iso639-2/php/code_list.php
