### ISSUE TITLE
Optionally reduce padding around icon and hide date to reduce height

### ISSUE THREAD

**Issue by xstrex** [pkissling/clock-weather-card#110]
**Is your feature request related to a problem? Please describe.**
No, just some more options to reduce the overall height of the card. 

**Describe the solution you'd like**
- an option to reduce padding on top & bottom of top most data (above and below icon) 
- an option to remove the date string, also to reduce overall height

**Describe alternatives you've considered**
Reducing forecast days is helpful, but empty real-estate around upper section is (optionally) unnecessary

**Additional context**
n/a

**Comment by pkissling** [comment]
hi there, 
thanks for the request. i don't have access to a laptop until the end of this year, hence i will not be able to work on the request.
i have the feeling that your request could easily be implemented using card-mod. did you give it a try already?

**Comment by xstrex** [comment]
I have not (yet), I just wanted to hit up the dev before going elsewhere. The request isn't critical, just nice to have.

**Comment by alexruffell** [comment]
I have been trying to find a way to make the card smaller, and my primary target was the excessive padding at the top of the card. I coincidentally found a way to make it somewhat smaller using card_mod:


```
type: custom:clock-weather-card
card_mod:
  style: |
    .card-content { 
       padding-top: 0px;
    }
entity: weather.openweathermap
sun_entity: sun.sun
weather_icon_type: line
animated_icon: true
forecast_days: 5
locale: en
time_format: 24
date_pattern: PPP
hide_today_section: false
hide_forecast_section: false

```
With and without the mod:

<img width="362" alt="image" src="https://user-images.githubusercontent.com/4006944/212521835-22bef744-af8b-4931-a741-5a937b8cf7f7.png">
<img width="353" alt="image" src="https://user-images.githubusercontent.com/4006944/212521843-fdaa4cf2-b0b4-474b-a4a6-78c592b35ed3.png">

**Comment by pkissling** [comment]
hi there, sorry for the late response. been quiet busy the last couple of weeks.
i think the issue is related to the fact that there is an optional title attribute, which allows you to define a title for the card.

there is some logic missing to reduce the padding, if the title was not provided.
will try to fix this shortly

**Comment by pkissling** [comment]
hi @xstrex,

after looking into the issue i realized that the padding is indeed required.
depending on the resolution (device) being used the card might be shrinked to a size where the text will otherwise hit the upper border of the card
<img width="297" alt="image" src="https://user-images.githubusercontent.com/33731393/213648089-83ab1853-6a6d-49de-bc5f-b98647c3543c.png">

hence i'd like to ask you to apply the solution proposed by @alexruffell (card-mod).
i think at some point i will implement logic to allow customisation to a point where people can even define custom css styling using card-configuration (yaml). though at this point i focus on getting the basic functionality of the card working and to smooth out the rough edges

for your other request (remove date), there is already a PR pending (#131). i will review and release it shortly.
