### ISSUE TITLE
Dumb Question... what do the bars actually mean?

### ISSUE THREAD

**Issue by vaderag** [pkissling/clock-weather-card#143]
I don't quite know where to post this, but I don't see it explained anywhere... 
I love the look of this, but what do the bars on each day actually mean?

![image](https://user-images.githubusercontent.com/17175988/213755638-612c8f09-4502-4df6-bda9-6c273808348d.png)

So this part - what does it indicate?
![image](https://user-images.githubusercontent.com/17175988/213755691-35ee223c-d444-4c44-acb8-3c3649fa0350.png)
 Seems to be temperature related, but what of the greyed bits? What does the circle indicate (maybe time? But it's 5pm here and mine is at the end?)

Thanks!

**Comment by deprecatedcoder** [comment]
The bars represent the temperature range for the day.

In your above image, the 9° on Thursday represents the low across all of the forecast days and the 21° represents the highs (i.e. all bars are from 9° to 21°).

The colored portion of the bar represents the range of temperatures that are forecast for that day (so 12° to 21° on Monday).

The circle represents the current temperature (16° or roughly midway between 12° and 21° in your case).

I love this card for that reason because it makes it very easy to see a "mostly hot day" versus a "mostly cold day"

It also makes it easy for me to be jealous of your temperate climate, as mine does not look so welcoming 🤣

![Screenshot 2023-01-21 011152](https://user-images.githubusercontent.com/13654313/213846390-53d2f0b1-6af0-493a-b2f8-2a3e14273296.png)

**Comment by vaderag** [comment]
> The bars represent the temperature range for the day.
> 
> In your above image, the 9° on Thursday represents the low across all of the forecast days and the 21° represents the highs (i.e. all bars are from 9° to 21°).
> 
> The colored portion of the bar represents the range of temperatures that are forecast for that day (so 12° to 21° on Monday).
> 
> The circle represents the current temperature (16° or roughly midway between 12° and 21° in your case).
> 
> I love this card for that reason because it makes it very easy to see a "mostly hot day" versus a "mostly cold day"
> 
> It also makes it easy for me to be jealous of your temperate climate, as mine does not look so welcoming 🤣
> 
> ![Screenshot 2023-01-21 011152](https://user-images.githubusercontent.com/13654313/213846390-53d2f0b1-6af0-493a-b2f8-2a3e14273296.png)

Awesome, thanks for the great explanation!

And sadly that is not my temperature - I took it from the GitHub page... 🤣
0°c here right now 😂
