### ISSUE TITLE
Ability to set a time zone

### ISSUE THREAD

**Issue by dhilbig** [pkissling/clock-weather-card#197]
**Is your feature request related to a problem? Please describe.**
When using a weather feed from a different time zone the time can only be linked to the browser or the HA servers time.

**Describe the solution you'd like**
I would like to be able to set a "time_zone:" parameter when I am using a card displaying the weather from a different time zone. This would allow the card to display the time, adjust the transition to the next day to match that of the forecast's origin and display the time zone sun / moon icons.

**Additional context**
As I live in Australia but have family living in Germany, I currently collect forecast data from the Australian Government's Bureau of Meteorology to display my local forecasts and Deutscher Wetterdienst for Germany's.

**Comment by pkissling** [comment]
might be done as proposed by @dhilbig or as proposed in #180

**Comment by pkissling** [comment]
hey there, i just released a [beta 2.0.0](https://github.com/pkissling/clock-weather-card/releases/tag/2.0.0) which adds the functionality to provide a custom `time_zone`. please carefully read the changelog. there are some breaking changes, which might require your attention.

**Comment by pkissling** [comment]
released 2.0.0

**Comment by untaught-mint-contact** [comment]
Hello, Looking for assistance with getting the **time_zone** setting working. The card config below results in showing my local date/time instead of US/Eastern. I look forward to any help. Thank you.

type: custom:clock-weather-card
entity: weather.ksgj_daynight
title: St. Augustine
sun_entity: sun.sun
temperature_sensor: sensor.outdoor_temp
weather_icon_type: line
animated_icon: true
forecast_rows: 5
locale: en-US
time_pattern: H:mm
time_format: 12
date_pattern: M/d/yyyy
hide_today_section: false
hide_forecast_section: false
hide_clock: false
hide_date: false
hourly_forecast: false
use_browser_time: false
time_zone: US/Eastern
state_color: true

**Comment by pkissling** [comment]
> Hello, Looking for assistance with getting the **time_zone** setting working. The card config below results in showing my local date/time instead of US/Eastern. I look forward to any help. Thank you.
> 
> type: custom:clock-weather-card entity: weather.ksgj_daynight title: St. Augustine sun_entity: sun.sun temperature_sensor: sensor.outdoor_temp weather_icon_type: line animated_icon: true forecast_rows: 5 locale: en-US time_pattern: H:mm time_format: 12 date_pattern: M/d/yyyy hide_today_section: false hide_forecast_section: false hide_clock: false hide_date: false hourly_forecast: false use_browser_time: false time_zone: US/Eastern state_color: true

setting `time_zone: US/Eastern` works for me. 
my local time is 21:42
<img width="451" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/33731393/d86f4090-ab40-4b35-8ba1-b2ece823ee9b">

**Comment by untaught-mint-contact** [comment]
Interesting. Well thank you.
