### ISSUE TITLE
Configuration/Install

### ISSUE THREAD

**Issue by memattyg** [pkissling/clock-weather-card#199]
Hi, sorry to clutter the board with this, but I am completely stuck trying to get step 5 (Add [configuration] for the card in your ui-lovelace.yaml or via the UI.) to work.  

I can not find the correct place to put the configuration in my HA.  Can someone please walk through the correct steps?

**Comment by pkissling** [comment]
hey @memattyg,

hope this helps. cheers

![image](https://github.com/pkissling/clock-weather-card/assets/33731393/5a3bb4af-dc5a-4b2d-a732-49fbd6e2d800)
![image](https://github.com/pkissling/clock-weather-card/assets/33731393/d0d63e8c-415b-4cec-bf35-34859a51f0aa)
![image](https://github.com/pkissling/clock-weather-card/assets/33731393/c28214f5-47dc-4053-8d7a-65d8d050a4a3)
![image](https://github.com/pkissling/clock-weather-card/assets/33731393/c2249bfe-6a9f-4365-a9c4-5e826e9a58ff)

**Comment by nickChenyx** [comment]
@pkissling i was blocked in same case, but my question is why clock-weather-card cann't edie in visual mode, and i don't have `weather.home` entity.  

In the end, i abandoned to edit in visual mode, just write yaml to config card. And i searched my entity list start with `weather.` and i got my weather entity named `weather.foreast_my_home`, may be i was already changed my weather entity time without my knowledge... but set `eneity:  weather.foreast_my_home` really work.

Write down these operations so that later users can refer to them.
