### ISSUE TITLE
New Time Pattern option doesn't refresh seconds

### ISSUE THREAD

**Issue by jarrah31** [pkissling/clock-weather-card#259]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
2.1

**Last working release (if known):**
N/A

**Browser and Operating System:**
Safari 16.6 on MacOS 13.5.2

**Description of problem:**
When specifying the following `time_pattern` option, the seconds number doesn't update every second, it only updates every minute or when the browser is refreshed.
```
  - type: custom:clock-weather-card
    entity: weather.home
    time_pattern: HH:mm:ss
```

![](https://user-images.githubusercontent.com/3072303/276369202-24f47198-38cd-4698-af8e-42e30a7a710d.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Hoping to have similar "seconds" functionality to this card: https://github.com/fufar/simple-clock-card

**Comment by Rudd-O** [comment]
The matter isn't just the seconds.  The clock can show seconds, but in my case (since the update to November HA), the card does not update at all.  Even when the card is configured to show browser time.  It's stuck there.  I LOVE how the clock looks like, and I want to continue using the card, but having a clock that is randomly half an hour behind is actually disruptive to my daily life.

I think the card should tick at least once per minute and update itself, and if seconds are called for, it should tick every second.  Are we missing some JS that does this?  Does there need to be a separation between updating the entity and updating the clock?

Thanks for filing this bug report!

**Comment by jarrah31** [comment]
Thank you @pkissling, I can confirm that the seconds are now refreshed every second.
