### ISSUE TITLE
Humidity is not displayed

### ISSUE THREAD

**Issue by matomatusov** [pkissling/clock-weather-card#341]
Hi,
I don't see the humidity sensor on the card.
I updated to 2.3.0. I added the sensor and set it to display.
Don't know what the problem might be?

![12](https://github.com/pkissling/clock-weather-card/assets/129114957/03c1718f-7efa-473c-a596-187d9efc9c53)

**Comment by pkissling** [comment]
hi @matomatusov, did you reset your browser cache already?
https://github.com/pkissling/clock-weather-card/issues/340

**Comment by matomatusov** [comment]
Hi, yes i reset the cache browser.

![image](https://github.com/pkissling/clock-weather-card/assets/129114957/394a65f2-e596-42dd-9072-b5f5b40f22e5)

**Comment by pkissling** [comment]
can you please provide your configuration yaml where you configure `clock-weather-card`

**Comment by matomatusov** [comment]
Hi,
I am sending you the configuration.

```
type: custom:clock-weather-card
entity: weather.iakovi2
title: Home
sun_entity: sun.sun
temperature_sensor: sensor.iakovi2_temperature
humidity_sensor: sensor.iakovi2_relative_humidity
weather_icon_type: line
animated_icon: true
forecast_rows: 5
locale: cs
time_pattern: HH:mm:ss
time_format: 24
date_pattern: ccc, d.MM.y
hide_today_section: false
hide_forecast_section: false
hide_clock: false
hide_date: false
show_humidty: true
hourly_forecast: false
use_browser_time: false
time_zone: null
```

**Comment by pkissling** [comment]
can you please provide a screenshot of your `sensor.iakovi2_relative_humidity` sensor from the developer console?

the weather entity exposes humidity as an integer value. my hunch is that your humidity sensor exposes a string `77.0%` instead of an integer value `77`
<img width="719" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/33731393/7dcf578f-c55c-429a-84ca-29e2f8feb6ca">

**Comment by matomatusov** [comment]
![image](https://github.com/pkissling/clock-weather-card/assets/129114957/b14671f0-678d-4758-a486-159519cc4f24)

**Comment by pkissling** [comment]
hmmm i don't see any issue with your HA setup. @rakasha681, when implementing this feature, have you tested whether your feature works with `temperature_sensor` supplied?  do you have an idea why it does not work?

i don't have a humidity sensor, hence i am not able reproduce the problem

**Comment by Marcwa19197** [comment]
Same issue on my side..

Humidity Sensor:
<img width="999" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/5463753/40fbb007-9e90-4992-8b4f-3d3511353d85">

Config:
```
type: custom:clock-weather-card
entity: weather.openweathermap
sun_entity: sun.sun
temperature_sensor: sensor.gw1100a_outdoor_temperature
humidity_sensor: sensor.gw1100a_humidity
show_humidty: true
weather_icon_type: fill
animated_icon: true
forecast_rows: 7
locale: de
time_format: 24
date_pattern: DDDD
hide_today_section: false
hide_forecast_section: false
hide_clock: false
hide_date: false
hourly_forecast: false
use_browser_time: false
```

**Comment by Marcwa19197** [comment]
Fixed it... there is a typo! We need to use "show_humidity: true" instead of "show_humidty: true"
@matomatusov This should fix it also for your config.
@pkissling : So it is just a typo in readme file...

<img width="525" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/5463753/93958916-0bee-4ca4-a12b-5ff6e43cb6dc">

**Comment by matomatusov** [comment]
Hi,
@Marcwa19197 and @pkissling 
Thanks for help. Yes, it was a typo of the show humidity.
