### ISSUE TITLE
Unable to use on levono smart clock 

### ISSUE THREAD

**Issue by styphonthal** [pkissling/clock-weather-card#380]
it cannot run on levono smart clock, may have had previously according to posts on Reddit. It states "card not found". Same dashboard works on PC, android phone, and fire tablets. 

**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by styphonthal** [comment]
Attempted to use fully kiosk browser and home assistant companion app, both latest versions.

**Comment by pkissling** [comment]
hi @styphonthal,

I'm afraid there is nothing i can do on my side. the root cause of the problem comes from the fact that your lenovo smart clock is running a pretty outdated browser version which is expected to cause compatibility issues. link to the old ticket: https://github.com/pkissling/clock-weather-card/issues/178#issuecomment-1888579836

if you have any on how to fix the issue, please let me know.
