### ISSUE TITLE
Card stops working with environment Canada integration

### ISSUE THREAD

**Issue by ronnienijjar** [pkissling/clock-weather-card#39]
The card stops working in the evening with environment Canada integration but comes back the next day. My assumption is this happens when the integration stops reporting the current days high temperature ( temperature: null)

**Comment by pkissling** [comment]
hey @ronnienijjar, 
i changed to card's logic to expect and handle null values in all forecast attributes.
though i was not able to reproduce to issue, since its a pretty edgy case (environment Canada weather provider & only happens in the evening / before midnight).

would you mind installing the fix manually and having it running for a couple of days? i would like to have your confirmation that the issue didn't occur with the fix

[clock-weather-card.js.zip](https://github.com/pkissling/clock-weather-card/files/9833325/clock-weather-card.js.zip)

i will have the PR pending until then #51

**Comment by ronnienijjar** [comment]
Its installed. I will report back in a couple days

**Comment by ronnienijjar** [comment]
It appears to be working now. Thanks
