### ISSUE TITLE
min/max temperature for today

### ISSUE THREAD

**Issue by cptcotton** [pkissling/clock-weather-card#42]
The (very beautiful) widget doesn't show the min/max-temperature for the current day. The weather-provider delivers this data as shown in the standard ha-widget.

**Comment by usernein** [comment]
Which weather provider are you using and with which mode (hourly, daily, onecall_hourly, etc)?

**Comment by pkissling** [comment]
thanks for reporting the issue. additionally to what @usernein asked i would also ask you to upload a screenshot of the card. for me it's not entirely clear what you mean with "doesn't show the min/max-temperature for the current day."

**Comment by cptcotton** [comment]
![69CDDD32-321C-48B0-BC7B-B14B3A697055](https://user-images.githubusercontent.com/5418733/197210902-625f5b87-5b96-421e-950d-dd8f71f25e4d.png)
As you can see in the attached Screenshot, the default HA Widget shows the min/max-temperature for today but your very beautifull widget only shows it for the upcoming days. 
I am using the Home (met.no) intigration but do not know where the mode is defined. I am very new to HA.

**Comment by cptcotton** [comment]
@pkissling, thank you for your friendly help. 
The yaml to the screenshot is

`- type: custom:clock-weather-card
        entity: weather.forecast_h14a
        locale: de
      - type: vertical-stack
        cards:
          - show_current: true
            show_forecast: true
            type: weather-forecast
            entity: weather.forecast_h14a_hourly
            name: Vorhersage Sillenstede
            theme: Animated Weather Card
          - show_current: false
            show_forecast: true
            type: weather-forecast
            entity: weather.forecast_h14a
            theme: Animated Weather Card`

Would it be possible to combine the data of weather.forecast_h14a and weather.forecast_h14a_hourly ?

**Comment by pkissling** [comment]
hey @cptcotton, your config pretty much explains why the data shown in the two cards is different.
considering the [faq](https://github.com/pkissling/clock-weather-card#why-dont-i-see-the-current-day-in-my-weather-forecast) i'd suggest you to switch to a different weather provider. i personally use OpenWeatherMap, which allows the card to render the forecast for the current day (as a bar).

i understand your request of making the card able to process data from multiple weather providers at the same time.

i only released this card roughly one week ago and my main priority at this point is to make sure that the card works without any issues and to smoothen rough edges here and there in order to make the card usable for a broad user base.

since the request of yours would make the card quiet complicated in terms of how data is being aggregated and also on how the card must be configured, i would keep this in enhancement in mind as a future improvement, but not implement it right away.

hope this is okay for you?

**Comment by cptcotton** [comment]
Thats ok, thanks for the support. I'll take a look at openwethermap.
