### ISSUE TITLE
Days do not advance

### ISSUE THREAD

**Issue by nightfever77** [pkissling/clock-weather-card#71]
I set this card up last Tuesday. Today we have Sunday, but I always saw and still see Tue-Sat. Why?

**Comment by pkissling** [comment]
hi @nightfever77, can you dump the state of your weather provider? 
are you on the lastest card version?

**Comment by nightfever77** [comment]
I am on 1.0.6
When I delete the card and add it again, it shows Tue-Sat.
Dump attached
[tomorrow_io_weather.txt](https://github.com/pkissling/clock-weather-card/files/9846123/tomorrow_io_weather.txt)

**Comment by pkissling** [comment]
interesting. can you please also attach a screenshot of the card?

**Comment by pkissling** [comment]
i can reproduce the problem using tomorrow.io weather provider. will have a look and get back to you. thanks for reporting the issue 
![Screenshot 2022-10-23 at 12 48 39](https://user-images.githubusercontent.com/33731393/197387929-18b2676a-dbf1-46f2-919c-249a7e17137d.png)

**Comment by pkissling** [comment]
i found the issue. tomorrow.io delivers forecasts for a lot of days in advance (like 14 oder so). the card had a bug where it would pick the last 5 days to show in the forecast (instead of the first 5 days). i fixed the bug and will release a new version in the new few days.

this is the how it will look like with tomorrow.io after the fix:
![Screenshot 2022-10-23 at 13 11 47](https://user-images.githubusercontent.com/33731393/197388810-0168ddb1-bf83-4036-98d3-f566121230c2.png)

**Comment by nightfever77** [comment]
Thanks much for the quick fix.
